"""add cover_image attribute in Game model

Revision ID: 4928cc709eb4
Revises: 915946009ad4
Create Date: 2025-05-17 07:44:39.268962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4928cc709eb4'
down_revision: Union[str, None] = '915946009ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'cover_image')
    # ### end Alembic commands ###
