"""add nullable=False in like_num

Revision ID: 56f9325a5e50
Revises: 30b4780a542b
Create Date: 2025-05-24 08:03:31.274127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56f9325a5e50"
down_revision: Union[str, None] = "30b4780a542b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 기존 NULL 값을 0으로 먼저 대체
    op.execute("UPDATE game_logs SET like_num = 0 WHERE like_num IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_logs",
        "like_num",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("game_logs", "like_num", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
