"""add 'is_deleted' and 'deleted_at' attributer

Revision ID: 5a3ad6103e34
Revises: bd438ab1bea0
Create Date: 2025-03-27 20:48:36.707542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a3ad6103e34"
down_revision: Union[str, None] = "bd438ab1bea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_index("ix_users_email", table_name="users")
    op.create_unique_constraint(None, "users", ["name"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
