"""add GameLogLike table

Revision ID: 7194e05d1fca
Revises: 4928cc709eb4
Create Date: 2025-05-19 12:21:24.978615

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7194e05d1fca"
down_revision: Union[str, None] = "4928cc709eb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_log_likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("game_log_id", sa.Integer(), nullable=True),
        sa.Column("flag", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["game_log_id"], ["game_logs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_name"], ["users.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name", "game_log_id", name="unique_game_log_like"),
    )
    op.create_index(
        op.f("ix_game_log_likes_id"), "game_log_likes", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_log_likes_id"), table_name="game_log_likes")
    op.drop_table("game_log_likes")
    # ### end Alembic commands ###
