"""change user_id to user_name and game_id to game_name in GameLog

Revision ID: 915946009ad4
Revises: a172d36ac4f1
Create Date: 2025-04-16 17:56:36.172645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915946009ad4'
down_revision: Union[str, None] = 'a172d36ac4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_logs', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('game_logs', sa.Column('game_name', sa.String(), nullable=True))
    op.drop_constraint('game_logs_game_id_fkey', 'game_logs', type_='foreignkey')
    op.drop_constraint('game_logs_user_id_fkey', 'game_logs', type_='foreignkey')
    op.create_foreign_key(None, 'game_logs', 'games', ['game_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_logs', 'users', ['user_name'], ['name'], ondelete='CASCADE')
    op.drop_column('game_logs', 'user_id')
    op.drop_column('game_logs', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_logs', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_logs', type_='foreignkey')
    op.drop_constraint(None, 'game_logs', type_='foreignkey')
    op.create_foreign_key('game_logs_user_id_fkey', 'game_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('game_logs_game_id_fkey', 'game_logs', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_column('game_logs', 'game_name')
    op.drop_column('game_logs', 'user_name')
    # ### end Alembic commands ###
