"""add unique attribute in Game.name

Revision ID: a172d36ac4f1
Revises: ed8bd85ef158
Create Date: 2025-04-16 17:56:11.876941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a172d36ac4f1'
down_revision: Union[str, None] = 'ed8bd85ef158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_name', table_name='games')
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.create_index('ix_games_name', 'games', ['name'], unique=False)
    # ### end Alembic commands ###
