"""add like_num attribute in GameLog

Revision ID: af2e9d7d115c
Revises: 7194e05d1fca
Create Date: 2025-05-19 13:02:03.308821

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af2e9d7d115c"
down_revision: Union[str, None] = "7194e05d1fca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_logs", sa.Column("like_num", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_logs", "like_num")
    # ### end Alembic commands ###
