"""add min_possible_num and max_possible_num in Game model

Revision ID: 2c0f140db188
Revises: 47518ee5585c
Create Date: 2025-02-18 20:59:09.001493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0f140db188'
down_revision: Union[str, None] = '47518ee5585c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('min_possible_num', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('max_possible_num', sa.Integer(), nullable=False))
    op.drop_column('games', 'possible_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('possible_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('games', 'max_possible_num')
    op.drop_column('games', 'min_possible_num')
    # ### end Alembic commands ###
